### ISSUE TITLE
[Feature] Autoconfig routine

### ISSUE THREAD

**Issue by lozalojo** [jvir/foundry-falemos#14]
A button to autoconfig falemos, with those parameters:

* Dimensions of the scene (width x height).
* Margins to leave at the left, top, right, bottom.
* Overlays for each camera: left, top, right, bottom in relationship to the camera (as in the configuration).
* Grid layout (3x2, 2x2, 2x1, 3x1, 4x2).
* Minimum separation between cameras.
* Position of the GM in the grid (1st, 2nd, 3rd,....).
* Empty slots (4 players + 1 GM with a 3x2 grid means that there must be one empty slot, decide if this slot is 1st, 4th, 6th,...).
* Frame to use
* Names: players names/1st owned actor's name.

**Comment by jvir** [comment]
In version 0.5.0 a button has been added to export the configuration to a macro for later reuse.

With this option you can create templates of configurations that you can use later. For example you create a 3-camera scene in the upper zone and export it to a macro. That macro can be used anywhere you want and it will copy the configuration, either the same world or another one.

I think this roughly covers this issue.

Thanks for the issue.
