### ISSUE TITLE
[Feature] Add obs.ninja iframes

### ISSUE THREAD

**Issue by lozalojo** [jvir/foundry-falemos#15]
To replace cameras, maybe it is possible for the autoroutine described here: https://github.com/jvir/foundry-falemos/issues/14
to read the ids of each camera having access to the management web of a given room at obs.ninja and input it in the falemos configuration.

**Comment by jvir** [comment]
OBS Ninja does not have the integration possibility necessary to use the same workflow in Falemos. The integration possibilities of OBS Ninja go through an iframe which is nothing more than an embedded external page which limits access and customisation in many aspects.

For these reasons this integration is currently ruled out.

**Comment by lozalojo** [comment]
Ok, thank you!
