### ISSUE TITLE
custom z-index cameras :)

### ISSUE THREAD

**Issue by ScriptFeliz** [jvir/foundry-falemos#16]
Hello falemos creators,

what a nice project is it, I have some issues when I want to put MJ camera in full screen, it hide the UI and we cannot change any more the resolution of the camera ... so I have to delete manually the scene from the folder.

Then, I want to use the camera as a background map picture to make improvisation RPG and have the possibility to use token on it.
I think of this is just a question of z-index, if it could possible to add it would be great !
  
![image](https://user-images.githubusercontent.com/4260341/116681638-8625e980-a9ad-11eb-801b-5829319dabfa.png)
:
also I didn't find a way to have possibility as MJ to desable camera of players, may be it could be nice to possibility to enable/disable each camera's players.

Thanks to you, 
what you do is great !

**Comment by jvir** [comment]
Camera to background feature complete in 0.8.0
