### ISSUE TITLE
Enhancement: Standard 'Table' Layout option

### ISSUE THREAD

**Issue by drveoj** [jvir/foundry-falemos#19]
Enhancement request: 
This module is great however while having per-scene video layouts is great I feel like we're missing the more general use case: Simulating a group of friends gathering around a table to play an RPG. 

I feel like we're missing that ability in foundry itself and this module comes close but the per-scene nature makes it impossible to lay out a 'table' with your 'scenes'/map in the center and flip between them as if we're turning over maps. 

At the very least it would be good to 'template' up a layout for re-use on scenes as per suggestions in #5

**Comment by jvir** [comment]
I agree. The approach I want to take to this is based on creating macros with presets.
Currently Falemos allows that once you have configured a scene you can create a macro with that configuration and apply it to the scene you want with a single click.
Taking into account this operation that currently allows what you are asking for, but at the cost of everyone having to do it, what I want is to create a compendium of presets as follows.


- Folder "2 Players".
  - Rectangular - Full width - No borders - No Effects
  - Hexagonal - 20% Stacked Top - NB - NE
 ...
- Folder "3 Players".
  ...

For this I would like the cooperation of the community as it would save me work to have it as soon as possible.

**Comment by jvir** [comment]
This can currently be done with the Vaccinator macro included in Falemos and created by Viriato139ac.
