### ISSUE TITLE
[Bug] Hide Functionality No Longer Hides Controls

### ISSUE THREAD

**Issue by Dick-K** [jvir/foundry-falemos#25]
The hide controls appear to only hide the chat side-bar. Navigation, quickbar etc are not hidden.

**Comment by jvir** [comment]
I am unable to reproduce this problem, can you give me more information?
- Foundry version
- Clean World?
- Was it used at some point in that Vaccinator scene? 
- Does crtl-alt-h work?

**Comment by Dick-K** [comment]
Thanks for such a quick response. I think I've found the source of the problem.

**Foundry Version**: 7.9
**Clean World?**: There appears to be a conflict with the _Lock View_ module:

If I disable _Lock View_ then Ctrl-Alt-H works as specified.
If I enable _Lock View_ then Ctrl-Alt-H renders the chat side-bar visible and invisible, _but regardless of whether the visibility check boxes are set in Falemos._
If I enable _Lock View_ and disable _Falemos_ then Ctrl-Alt-H does nothing, as expected.

**Was it used at some point in that Vaccinator scene?**: I did try out Vaccinator, and then used the macro function afterwards. This was when I encountered the bug.
**Does crtl-alt-h work?**: Yes, but only if I disable the _Lock View_ module. See above.

**Comment by jvir** [comment]
I'll have a look at lock view to see if I can make them compatible.

**Comment by lozanoje** [comment]
@Dick-K , do you mind testing if this problem still persists on v10?

**Comment by Dick-K** [comment]
It seems to be fixed now. With _Lock View_ also installed I can now still use Falemos to hide all screen widgets. There is another bug regarding the Fit to Contain/Fit to Cover config,, I'll raise that separately.
