### ISSUE TITLE
[Bug] Login Errors and New Copy of Vaccinator Macro Created Every Time a Player Logs In

### ISSUE THREAD

**Issue by Dick-K** [jvir/foundry-falemos#29]
I have updated to v0.8.0 of Falemos.

Regardless of whether _Falemos_ is enabled on a scene, each time a player logs into the game, the following occurs:
1) their screen displays two identical red messages:
"Error: User <username> lacks permission to update Macro <macro id>"

2) a new copy of the Vaccinator macro is created in the macro directory giving that player owner permission on the macro

**Update**
Apologies, on subsequent logins only one error message is issued. Also, no more copies of the Vaccinator macro are created in the macro directory. Although the player can drag the Vaccinator macro onto their quickbar, if they attempt to run it an error message is displayed:

"Error: user <username> lacks permission to update scene <scene id>"

...which is fine. Not sure the macro should be created though, except for the GM.

**Comment by jvir** [comment]
You are right, the macro should only be created/updated by the GM. I will upload patched version tomorrow (West Europe).

**Comment by Dick-K** [comment]
Thanks for fixing this jvir!
