### ISSUE TITLE
Change active scene activation trigger

### ISSUE THREAD

**Issue by Gorvaine** [jvir/foundry-falemos#3]
Falemos activation trigger is "active" scene.

For multi-scene purposes this is counter-intuitive.

For example: If you have a Falemos scene active, and you want to see a map on a different scene, cameras still will be on the middle of the screen preventing you to see anything else.

Falemos should be activate depending on which scene the player is.

**Comment by jvir** [comment]
Fixed in 0.2.0

Thanks for the report.
