### ISSUE TITLE
Hide cameras

### ISSUE THREAD

**Issue by Gorvaine** [jvir/foundry-falemos#32]
Option to hide all the cameras in the scene. #

**Comment by jvir** [comment]
I label this as an enhancement. Actually this is possible by indicating in the scene negative values for the camera position.

**Comment by lozalojo** [comment]
> Option to hide all the cameras in the scene. #

It has been implemented on the new version of Vaccinator script, just set the order of desired players to 0 and Vaccinator will hide the cameras.
