### ISSUE TITLE
Macro creation function does not export "enable" tag

### ISSUE THREAD

**Issue by lozalojo** [jvir/foundry-falemos#36]
On a newly created scene, if I export to a macro current config:

```js
let sceneData = `{"hide":{"mode":"scene"}}`; 
game.falemos.putSceneConfig(null, sceneData);
```

It does not export the falemos "enable" state, right macro (if you plan to create a macro to just disable falemos) should be:

```js
let sceneData = `{"hide":{"mode":"scene"}, "enable": false}`; 
game.falemos.putSceneConfig(null, sceneData);
```

**Comment by jvir** [comment]
Hello, lozalojo.

I'm having trouble understanding the issue, could you give me a more detailed explanation?

**Comment by lozalojo** [comment]
Create new scene, do not configure anything related to falemos, just go to options and clic Create macro; the macro created is this one:

```js
let sceneData = `{"hide":{"mode":"scene"}}`; 
game.falemos.putSceneConfig(null, sceneData);
```

As you can see, the falemos config string for that macro does not include "enable":false (which is the configuration by default of falemos, to be disabled).

What I'm saying is that the macro should include that tag:

```js
let sceneData = `{"hide":{"mode":"scene"}, "enable": false}`; 
game.falemos.putSceneConfig(null, sceneData);
```
Why to create a dummy config macro? To switch easily between a falemos config and the defaults, with a click you position the cameras and with another button you turn falemos off

**Comment by jvir** [comment]
Actually, as long as there is no saved configuration you should not export any value of any field.

The hide -> mode = scene is from an old code that is not used, in next versions it will disappear and if you export the configuration in a new scene that does not have it saved it will not be seen.

It may be better to use "create macro" to save the scene and then export.

**Comment by lozalojo** [comment]
Estoy hablando de macros, no exporto nada, simplemente creo una macro para deshabilitar falemos y otra con las cámaras configuradas, las pongo en la barra y tengo un botón para deshabilitar y otro para habilitar con el formato que quiero.

Pero para crear la macro "deshabilitar falemos" la creo dejando las opciones vacias y dándole al botón pertinente de crear macro, pero como no exporta la clave "enable":false entonces la macro creada no hace lo que quiero, porque no deshabilita nada.

Entonces, creo que estaría bien una opción para deshabilitar rápidamente falemos (combinación de teclas o una macro tal que así).

```js
let sceneData = `{"enable": false}`; 
game.falemos.putSceneConfig(null, sceneData);
```

**Comment by jvir** [comment]
Veamos, que estoy espeso:

- Cuando esta configurado Falemos en una escena (se ha guardado la configuración) el botón "crear macro" exporta el parametro enable adecuadamente.
- Cuando NO está se configuro nunca una escena con Falemos (nunca se guardo la configuración) el botón "crear macro" exporta una opción que no se usa y no debería exportarse y lo demás vacío.

A partir de aquí lo que entiendo es que quieres una forma de:
- O tener una macro que habilite y deshabilite Falemos sin tocar ninguna otra configuración.
- O poner un atajo de teclado para lo mismo.

Si es así, mi opción es un atajo de teclado "ctrl+alt+d(isable)"

**Comment by lozalojo** [comment]
Macro/atajo que habilite yo creo que no hace falta, solo una que lo deshabilite.

**Comment by jvir** [comment]
En Falemos 0.8.6 se ha creado el atajo ctrl+alt+d que des/habilita falemos
