### ISSUE TITLE
Falemos Disables Ability to Specify Own Font for CoC Sheet

### ISSUE THREAD

**Issue by Dick-K** [jvir/foundry-falemos#41]
**Describe the bug**
Since the latest release of the CoC7 system, 0.6.6, wiith Falemos enabled, any font I specify for use on the main sheet on the CoC config panel is ignored and the sheet uses the default font. With Falemos disabled in the Manage Modules section, the sheet uses the font(s) I specify.

**To Reproduce**
Run a CoC7 world.
Specify a font of choice in the CoC7 sheet configuration. I use locally stored fonts: **url('./userdata/fonts/Cristoforo.ttf') format('truetype')**

**Expected behavior**
The sheet uses the font(s) that are specified.

**Screenshots**

Falemos Disabled
![image](https://user-images.githubusercontent.com/73724728/132098356-65751b33-2702-471d-a948-fcfe55c1cf65.png)

Falemos Enabled
![image](https://user-images.githubusercontent.com/73724728/132098450-e393f5bd-0e5e-4c72-90ba-d77df36928c7.png)

**Version**
Foundry: 0.8.9
Falemos: 0.8.9

**Browser [e.g. chrome, safari]:**
Chrome
 
**Additional context**
Have mentioned this on the Foundry #chaosium channel and Viriato's implementation worked. He suggested I change the font path to one relative to the CoC7 system folder but that did not correct the problem. 

 This also occurred with the previous version of Falemos.

**Edit**: Falemos also disables the ability on the CoC7 sheet to disable the truncation of long skill names.

Falemos Disabled
![image](https://user-images.githubusercontent.com/73724728/132098821-ef99ad0f-a7d0-440d-b78b-f249bf854c15.png)

Falemos Enabled
![image](https://user-images.githubusercontent.com/73724728/132098799-7a690ab9-5ffc-4cfa-8498-f140fdd72c53.png)

**Comment by Dick-K** [comment]
Hi jvir, JamesB on the CoC7 system dev team has identified an issue with another module for which they will soon implement a fix. He says that this will probaby fix this issue as well. I'll keep you posted. Hopefully, this won't require any involvement from you. All the best.

**Comment by jvir** [comment]
Thank you for the report. As finally it seems to be a problem with another module in principle I will close it and if after the fix in CoC7 we still have problems we will look at it.

**Comment by Dick-K** [comment]
Hi jvir, I just wanted to confirm that the latest release of the CoC7 system has successfully resolved its interaction with _Falemos_ and my custom font now displays correctly on the sheet.

All the best.
