### ISSUE TITLE
[Bug] Window size not lower than 10 percent

### ISSUE THREAD

**Issue by lozalojo** [jvir/foundry-falemos#45]
**Describe the bug**
When I set the width to a value lower than 10%, it uses 10% value always.

**To Reproduce**
Set width to 5%, the window will be 10%

**Foundry versión:**
Foundry 0.8.9
CoC 0.6.7

**Browser [e.g. chrome, safari]:**
 Edge

**Additional comment**
After set to 5% if you click F5 the window resizes to 5%, the real value of the width.
It is not updated when saving Falemos values from the scene config.

**Comment by lozanoje** [comment]
Fixed with:

https://github.com/jvir/foundry-falemos/commit/f94313d65be5026ddc499eb472ceebd37d894e66
