### ISSUE TITLE
[Bug] Sound glitch when aplying falemos config macro

### ISSUE THREAD

**Issue by lozalojo** [jvir/foundry-falemos#46]
**Describe the bug**
When I click in a macro with a falemos config, the volume of the A/V is stuck at its max and it is not possible to lower the volume.

**To Reproduce**
Save macro, place at the bottom bar, click on the macro.

**Foundry versión:**
Foundry 0.8.9
CoC 0.6.7

**Browser [e.g. chrome, safari]:**
 Edge + Chrome + Filezilla

**Additional comment**
After clicking the macro the config is restored and the volume cant be set manually, but clicking F5 and refreshing solves the problem, and the volume can be increased/decreased as normal.

**Comment by lozanoje** [comment]
Volume bar seems that has been removed at v10 and this bug no longer holds
