### ISSUE TITLE
possible incompatibility between falemos + ratas en las paredes

### ISSUE THREAD

**Issue by montver** [jvir/foundry-falemos#47]
possible incompatibility between phalemos + rats on the walls. When I deactivate falemos the system uses its own template and the images are not the correct size. 

![image](https://user-images.githubusercontent.com/72754407/137628297-596b171f-9352-4824-b05f-820722e60e18.png)

**Comment by lozanoje** [comment]
@montver , _Ratas en las paredes_ is not compatible anymore with v10, so I close this issue. In case RELP is again v10-enabled, please, test it and report back
