### ISSUE TITLE
Camera to background possible bug 

### ISSUE THREAD

**Issue by Mingus-Analingus** [jvir/foundry-falemos#50]
When camera to background is used with my OBS virtual camera the grid, tokens, drawings, etc. are all covered. 
I.E the image is not in the background as such. 

This is occurs independently of other modules and the foundry version used is foundry version 9, build 269

Screenshots: 
obs window in camera view, token is visible. 
![image](https://user-images.githubusercontent.com/95985595/174530634-388619a7-13f1-4be0-a1c4-621e01409be2.png)
Camera to background enabled, token is covered. 
![image](https://user-images.githubusercontent.com/95985595/174530711-1bfd8a6f-e0c2-4736-aad6-df1956d6d926.png)

**Comment by bklick** [comment]
I am also experiencing this.

**Comment by lozanoje** [comment]
@Mingus-Analingus , @bklick , do you still have this issue on v10 and latest version?

I cant reproduce it

**Comment by lozanoje** [comment]
No news, good news!
