### ISSUE TITLE
Fit to Cover and Fit to Contain Disable Falemos Presentation

### ISSUE THREAD

**Issue by Dick-K** [jvir/foundry-falemos#58]
**Describe the bug**
Using either **Fit to Contain** or **Fit to Cover** causes Falemos to ignore position and border specifications for that user/scene combination.

**To Reproduce**
1. Set up a scene (need only be for one user) with a camera window using a Falemos border and specify its position
2. Ensure **No Fit** is specified. Note that Falemos displays the camera as expected.
3. Specify either **Fit to Contain** or **Fit to Cover** for the camera. It will initially display the correct Falemos camera border and position.
4. Press F5 to reinitialise the Foundry process. Note that the camera window has reverted to its non-Falemos positioning and default Foundry border. Resetting the cover to **No Fit** and pressing F5 reverts to the correct Falemos presentation.

**Expected behavior**
**Fit to Contain** or **Fit to Cover** should leave the Falemos presentation as specified.

**Screenshots**

**Foundry versión:** 10.291

**Browser [e.g. chrome, safari]:** Chrome
 
**Additional context**

**Comment by lozanoje** [comment]
Fixed with https://github.com/jvir/foundry-falemos/pull/61
