### ISSUE TITLE
camera view is forcibly reset for all players upon refreshing

### ISSUE THREAD

**Issue by Mingus-Analingus** [jvir/foundry-falemos#71]
**Description**

Whenever a player leaves or rejoins the game, the camera position (the position of the screen, not the webcam feed) resets for all other players and the GM. If you have a default camera view set up for a map, it will recenter the view there. 

The console will also print this error message, occasionally, after the view rest. However I could not reproduce this reliably.
"foundry.js:78177 Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable"

To clarify, we run foundry on a server.  

**To Reproduce**
1. Launch a world with Falemos enabled. 
2. Join with the GM profile and any player profile (or yourself from another window) 
3. Activate a scene with Falemos enabled, such that both the player and GM can see the scene.
4. refresh either window while in a scene. 

**Expected behavior**
The camera position for the participant who did not refresh will forcibly reset to the map's default position every time the other refreshes. 

**Media**
Screenshot of the console error
![image](https://user-images.githubusercontent.com/95985595/224577910-89d8ec0e-7a9f-491e-8ee1-7c77fc172db0.png)
Video of this error being produced in two chrome windows.
https://imgur.com/a/1QoJmNC
**Foundry versión:**

V10.291
**Browser [e.g. chrome, safari]:**
 Chrome, but also reproducible in Firefox.
**Additional context**

**Comment by lozanoje** [comment]
Yes, I introduced that behaviour intentionally on the lastest version because I found that enabling/disabling falemos while in-game produces a strange effect misaligning left buttons and consequently forces the background image to an undesirable position, so the only solution I found was to refresh and reset position.

I will check if there is a workaround to avoid reseting background image to default

**Comment by lozanoje** [comment]
Fixed in last release
