### ISSUE TITLE
Activating a non-falamos active scene from a falamos active scene doesn't return camera to the dock. 

### ISSUE THREAD

**Issue by TheXeno30** [jvir/foundry-falemos#79]
**Describe the bug**
Activating a non-falamos active scene from a falamos active scene doesn't return camera to the dock. 
![image](https://github.com/user-attachments/assets/941d759f-91c2-48cd-9551-c869b4352f9c)

New scene:
![image](https://github.com/user-attachments/assets/2b5543f2-a01f-4e6c-871a-dd5f0a8525b2)

should be 
![image](https://github.com/user-attachments/assets/469ed8cf-5203-4e89-962c-b6ea6bd04a82)

**To Reproduce**
1. Go to falamos active page
2. Click on activate another non-falamos active page
3. See error

**Expected behavior**
camera is moved to the dock

**Screenshots**

**Foundry versión: V12 - D&D 3.3.1

**Browser [e.g. chrome, safari]: Chrome
 
**Additional context**

**Comment by lozanoje** [comment]
Sorry, I didnt notice this issue since I am not the owner of the repository, I've just tested and was fixed in the latest version, if error persists, please reopen the issue
